a.exe: node.o istack.o main.o
	g++ -g node.o istack.o main.o

node.o: node.cpp node.h
	g++ -c -g node.cpp

istack.o: istack.cpp istack.h node.h
	g++ -c -g istack.cpp

main.o main.cpp istack.h
	g++ -c -g main.cpp